[package]
name = "parterm"
version = "0.1.1"
authors = ["Razvan Rotari <razvanrotari@posteo.net>"]
license = "MIT"

[dependencies]
libc = "0"
termion = "1"
chan-signal = "0"
clap = "2.33.3"

[[bin]]
name = "parterm"
doc = false
